name: CI/CD of proyect

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run RuboCop
        run: |
          bundle exec rubocop --format simple --fail-level W
  rspec:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run RSpec
        run: |
          bundle exec rspec
